#!/bin/bash

# nom: pgvm_list
# Génération d'une liste de VM
# ce script doit être appelé depuis le script maitre pgvm

# -x pour debug
set +x

# désactive l'interprétation de '!' dans une chaine
set +H

#echo PVUSER=$PVUSER

# argument id 5+3

#if [ "$1" = "" ]
#then
#	echo "Erreur, donner votre id 5+3 en argument"
#	exit 1
#fi
#PVUSER=$1

OUT=out_all.csv

if [ -f $OUT ]; then rm $OUT; fi


TODAY=$(date '+%Y%m%d_%H%M%S')
CURLLOG=/tmp/proxmox/curl_$TODAY.log

#---------------------------------------------------------------------------
function process()
{
#	echo "process $1"
	curl -k --silent \
		-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$1/qemu | jq -r '.data[]' >out_$1.json 2>>$CURLLOG
	err=$?
	if ! [ $err = 0 ]
	then
		echo "node '$1': echec!"
		exit 1
	fi
	jq -r '(.vmid|tostring) + ";" + .name + ";" + .tags + ";" + (.template|tostring)' < out_$1.json >out_$1.csv

# Ajout nom node en tete du csv
	IFS=";";while read line;
	do
		echo "$1;${line}" >> $OUT
 	done < out_$1.csv

# extraction des template de chaque node
	NBT=0
	if [ -f template_$1.csv ]; then rm template_$1.csv; fi
	IFS=";";while read -a ARR
	do
#		echo "0:${ARR[0]} - 1:${ARR[1]} - 2:${ARR[2]} - 3:${ARR[3]}"
		if [ ${ARR[3]} = 1 ]
		then
			NBT=$((NBT+1))
			echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> template_$1.csv
			echo "$1;${ARR[1]};${ARR[2]};${ARR[0]}" >> template_all.csv
		fi

# comptage de tags
		if ! [ "${ARR[2]}" = "" ]
		then
			tag=${ARR[2]}
			((TAGARR[$tag]++))
		fi

	done < out_$1.csv
	echo " -node '$1': $(wc -l <out_$1.csv) machines, dont $NBT template(s)"

# Génération d'un CSV contenant tous les tags (format à définir?)
	IFS=";";while read -a ARR
	do
		echo "${ARR[3]}">>tags2.csv
	done <$OUT
	sort tags2.csv >tags1.csv
	uniq tags1.csv >tags.csv
}
#---------------------------------------------------------------------------


# liste des nodes 
echo "-Récupération liste des nodes..."
curl --silent -k \
	-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
	https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes|jq | jq -r '.data[] | .node' >nodes.csv 2>>$CURLLOG

echo "-Nodes accessibles: $(wc -l < nodes.csv)"

if [ -f tags2.csv ]; then rm tags2.csv; fi
if [ -f template_all.csv ]; then rm template_all.csv; fi

# associative array used to count tags
declare -A TAGARR

while read -r nodename
do
#	echo "process node $nodename"
	process $nodename
done < nodes.csv

echo "-Nb templates: $(wc -l<template_all.csv)"
echo -e "\n Available templates:"
printf "| %10s | %13s | %15s | %7s |\n" Node Name Tags VMid
echo "|------------|---------------|-----------------|---------|"
IFS=";";while read -a ARR
do
	printf "| %10s | %13s | %15s | %7s |\n" ${ARR[0]} ${ARR[1]} ${ARR[2]} ${ARR[3]}
done < template_all.csv
echo "|------------|---------------|-----------------|---------|"


echo -e "\n-Nb occurences des tags"
for i in "${!TAGARR[@]}"
do
	echo "${i}=${TAGARR[$i]}"
done

exit 0




