#!/bin/bash

# nom: pgvm_create
# ce script doit être appelé depuis le script maitre pgvm

# Script de gestion d'un ensemble de machines


# désactive l'interprétation de '!' dans une chaine
set +H


#================================================================
function CheckError()
{
#	echo "response=$response"
	if ! [ $err = 0 ]; then
		echo "Curl error: $err, server response=-$response-"; exit 1
	fi
	echo "$response" >>$CURLLOG
}

#================================================================
# re-create an array holding the nodes names
unset NODEARR
declare -a NODEARR
while read -r nodename
do
	NODEARR+=($nodename)
done < data_nodes.csv


DONE=NO
while [ $DONE = NO ]
do
	BASENODE=$(zenity --list --text="Choisissez le noeud où se trouve le\ntemplate et où créer les VMs" --column="nodes" ${NODEARR[@]})
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	echo "BASENODE=$BASENODE"

	if ! [ -f data_template_$BASENODE.csv ]
	then
		echo "Aucun template disponible sur le noeud '$BASENODE'"
	else
		DONE=YES
	fi
done

# construction chaine contenant les noms des templates
unset TEMPLATES
declare -a TEMPLATES
IFS=";";while read -a ARR
do
#	echo "TEMPLATES=$TEMPLATES ARR[0]=${ARR[0]}"
	x=${ARR[0]}
	TEMPLATES+=($x)
done < data_template_$BASENODE.csv

#echo "t=${TEMPLATES[@]}"

TEMPLATE=$(zenity --list --text="Quel template à utiliser?" --column="templates" ${TEMPLATES[@]})
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "TEMPLATE=$TEMPLATE"

# récupération du vmid du template
IFS=";";while read -a ARR
do
	if [ ${ARR[0]} = $TEMPLATE ]
	then
		TVMID=${ARR[2]}
	fi 
done < data_template_$BASENODE.csv

echo "TVMID=$TVMID"

DONE=NO
while [ $DONE = NO ]
do
	MOD=$(zenity --entry --text "Donner le nom du module (RXXX, SAETTT)\n(servira pour le nom des VM)")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi
	if [ ${#MOD} = 0 ]; then
		echo "Erreur, ne peut pas rester vide!"
	else
		DONE=YES
	fi
done

echo "MOD=$MOD"


DONE=NO
while [ $DONE = NO ]
do

	TAGS=$(zenity --entry --text "Donner les tags a associer aux VMs, séparés par des virgules\n(pas d'espaces dans les tags!!)")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi
	echo "TAGS=$TAGS"
	if [ ${#TAGS} = 0 ]; then
		echo "Erreur, donner au moin un tag!"
	else
		DONE=YES
	fi
done

DONE=NO
while [ $DONE = NO ]
do
	ID=$(zenity --entry --text "Donner l'identifiant commun à ce set de VM, entre 00 et 99\n(ne doit pas déja exister)")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi
	echo "ID=$ID"

	if ! [ 2 = ${#ID} ]
	then
		echo "Erreur, l'identifiant doit être entre 00 et 99"
#		exit 1
	else
		DONE=YES
	fi
done



# create an array holding the group names, just for the zenity call below
unset GROUPARR
declare -a GROUPARR
while read -r group
do
	GROUPARR+=($group)
done < data_groups.csv
echo "GROUPARR=${GROUPARR[@]}"

GROUPSEL=$(zenity --list --text "Quel groupe d'utilisateurs?" --column="Groupe" ${GROUPARR[@]} )
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "GROUPSEL=$GROUPSEL"
VMNAMES="${MOD}-XXX (avec XXX l'id user)"
NB=$(wc -l <data_group_${GROUPSEL}.csv)

MSGT="Ok pour créer $NB VM\n- sur le node $BASENODE,\n- nommées ${VMNAMES},\n- basées sur le template $TEMPLATE,\n- "
if [ ${#TAGS} = 0 ]; then
	MSGT=${MSGT}"sans tags associés?"
else
	MSGT=${MSGT}"ayant les tags '$TAGS'?'"
fi

START=$(zenity --question --text "$MSGT")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

YEARDAY=$(date '+%y%j')
TODAY=$(date '+%Y%m%d_%H%M%S')
NUMA=1

IFS=";";while read -a ARR
do
	IDU1=${ARR[0]}
	IFS='@'; read -ra ARR2 <<< "$IDU1"; IFS=';'
	IDU=${ARR2[0]}
	NUMB=$NUMA
	if [ 1 = ${#NUMA} ]; then NUMB="0$NUMA";fi
	VMID=${YEARDAY}${ID}${NUMB}
	VMNAME=${MOD}-${IDU}
	echo "IDU1=$IDU1 IDU=$IDU VMID=$VMID VMNAME=$VMNAME"

	if [ "$DEBUG" = "Y" ]; then
		echo "-Create clone on node $BASENODE (Id=$TVMID): name=${VMNAME}, id=$VMID"
	fi
	DESC="VM Cloned from template $TEMPLATE (Id=$TVMID), created on $TODAY by user $PVUSER"
	
	echo " -Clonage VM depuis $TEMPLATE, nom=$VMNAME"
# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone
	response=$(curl -k \
		--silent -X POST \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$TVMID/clone" \
		--data-urlencode node=$BASENODE \
		--data-urlencode vmid=$TVMID \
		--data-urlencode newid=$VMID \
		--data-urlencode name=$VMNAME \
		--data-urlencode description="$DESC")
	err=$?
	CheckError

	echo " -Ajout des tags"
	response=$(curl -k \
		--silent -X POST \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$VMID/config?node=$BASENODE&vmid=$VMID&tags=$TAGS")
	err=$?
	CheckError


	echo " -configuration permissions (roles)"
# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/access/acl
	response=$(curl --insecure --silent \
		-X PUT \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		--data-urlencode "path=/vms/$VMID" \
		--data-urlencode "users=$IDU1" \
		--data-urlencode "roles=PVEVMUser;PVEVMAdmin" \
		--data-urlencode "propagate=1" \
		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/acl")
	err=$?
	CheckError

	((NUMA++))
done <data_group_${GROUPSEL}.csv

exit 0


