#!/bin/bash

# nom: pgvm_delete
# ce script doit être appelé depuis le script maitre pgvm

# !!!!!!!!!!!! WIP !!!!!!!!!!!!



# désactive l'interprétation de '!' dans une chaine
set +H


declare -a TAGARR

if ! [ -f data_tags.csv ]
then
	echo "Erreur, fichier 'data_tags.csv' inaccessible"
	exit 1
fi

IFS=";";while read TAG
do
	TAGARR+=($TAG)
done <data_tags.csv
echo "TAGARR=${TAGARR[@]}"	


TAGDEL=$(zenity --list --text="Quel machines ayant le tag ci-dessous souhaitez-vous détruire?" --column="tags" ${TAGARR[@]})
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

echo "TAGDEL=$TAGDEL"

START=$(zenity --question --text \
	"Ok pour effacer toutes les VM associées au tag $TAGDEL?")

if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "START=$START"
#exit 1

#-------------------------
# Suppression des machines

set +x
COMPT=0
IFS=";";while read -a TAB
do
	if ! [ "${TAB[3]}" = "" ]; then
		IFS=","; read -r -a TAGS <<< "${TAB[3]}"; IFS=";"
		for ((i=0; i<${#TAGS[@]}; i++))
		do
			tag=${TAGS[$i]}
#				echo "node ${TAB[0]}: machine ${TAB[2]}, tag=$tag"
			if [ $tag = $TAGDEL ]; then
				if [ "${TAB[4]}" = "1" ]; then
					echo "node ${TAB[0]}: machine ${TAB[2]}, id=${TAB[1]} est un template, pas de suppression"
				else
					echo "node ${TAB[0]}: suppression machine ${TAB[2]}, id=${TAB[1]}"
					response=$(curl --insecure --silent -X DELETE \
						-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
						"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}")
					err=$?

					if [ $err != 0 ]; then
						echo "Error: failure of delete operation, err=$err, response='$response'";
						exit 1
					fi
					((COMPT++))
				fi
			fi
		done
	fi
done <data_out_all.csv

echo "-$COMPT VM supprimées"
exit 0


