#!/bin/bash

# nom: pgvm_create
# ce script doit être appelé depuis le script maitre pgvm

# Script de gestion d'un ensemble de machines

# !!!!!!!!!!!! WIP !!!!!!!!!!!!


# désactive l'interprétation de '!' dans une chaine
set +H

YEARDAY=$(date '+%y%j')

ISOK=$(zenity --question --text "L'inventaire des machines est-il à jour?")
if [ $? != 0 ]; then
	./exportVM.sh PVUSER
fi
echo "ISOK=$ISOK"

# re-create an array holding the nodes names
declare -a NODEARR
while read -r nodename
do
	NODEARR+=($nodename)
done < nodes.csv

NODE=$(zenity --list --text="Choisissez le noeud où créer la VM" --column="nodes" ${NODEARR[@]})
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

echo "NODE=$NODE"

# Afficher la liste des templates dispos sur ce noeud
if ! [ -f template_$NODE.csv ]
then
	echo "Aucun template disponible sur ce noeud"
	exit 1
fi

# construction chaine contenant les noms des templates

declare -a TEMPLATES
IFS=";";while read -a ARR
do
	echo "TEMPLATES=$TEMPLATES ARR[0]=${ARR[0]}"
	x=${ARR[0]}
	TEMPLATES+=($x)
done < template_$NODE.csv


echo "t=${TEMPLATES[@]}"

TEMPLATE=$(zenity --list --text="Quel template à utiliser?" --column="templates" ${TEMPLATES[@]})
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "TEMPLATE=$TEMPLATE"

# récupération du vmid du template
IFS=";";while read -a ARR
do
	if [ ${ARR[0]} = $TEMPLATE ]
	then
		VMID=${ARR[2]}
	fi 
done < template_$NODE.csv

echo "VMID=$VMID"


NB=$(zenity --entry --text "Combien de VM?")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

#echo "NB=$NB"
i=$NB
((i++))
((i--))
if ! [ "$i" = "$NB" ];
then
	zenity --error --text "invalid value '$NB'"
#	echo "Erreur: valeur '$NB' invalide"
	exit 1
fi


MOD=$(zenity --entry --text "Donner le nom du module (RXXX, SAETTT)\n(servira pour le nom des VM)")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "MOD=$MOD"


TAGS=$(zenity --entry --text "Donner les tags a associer aux VMs, séparés par des virgules")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "TAGS=$TAGS"

ID=$(zenity --entry --text "Donner l'identifiant commun à ce set de VM, entre 00 et 99\n(ne doit pas déja exister)")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "ID=$ID"

if ! [ 2 = ${#ID} ]
then
	echo "Erreur, l'identifiant doit être entre 00 et 99"
	exit 1
fi

NB2=$NB
if [ $NB -lt 10 ]; then NB2=0$NB; fi

START=$(zenity --question --text \
	"Ok pour créer $NB VM, nommées ${MOD}-01 à ${MOD}-${NB2}, basées sur le template $TEMPLATE et ayant les tags '$TAGS'?")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi
echo "START=$START"


#-------------------------
# Creation des clones
IFS=$'\n'
for i in $(seq 1 $NB)
do
	NUM=$i
	if [ 1 = ${#i} ]; then NUM="0$i";fi
#	echo "i=-$i- NUM=-$NUM-, size=${#NUM}"
	echo "CREATION CLONE i=$NUM, nom=${MOD}-${NUM}, id=${YEARDAY}${ID}${NUM}"

# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone
	response=$(curl -k \
		--silent -X POST \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/clone?node=$NODE&vmid=$VMID&newid=${YEARDAY}${ID}${NUM}&name=${MOD}-$i")
	err=$?
	echo "response=-$response- err=$err"
	if ! [ $err = 0 ]; then exit 1; fi

	echo "Ajout des tags"
# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config
	response=$(curl -k \
		--silent -X POST \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/config?node=$NODE&vmid=$VMID&tags=$TAGS")
	err=$?
	echo "response=$response err=$err"
	if ! [ $err = 0 ]; then exit 1; fi

done

exit 0
