#!/bin/bash

# nom: pgvm_list
# Generates all the data of a cluster: list of nodes, VM, templates, users, groups, ...
# Must be called from master script: pgvm

# -x pour debug
set +x

# désactive l'interprétation de '!' dans une chaine
set +H

OUT=data_out_all.csv

if [ -f $OUT ]; then rm $OUT; fi


TODAY=$(date '+%Y%m%d_%H%M%S')
CURLLOG=/tmp/proxmox/curl_$TODAY.log

#---------------------------------------------------------------------------
# This function is called for each node of the cluster
function process()
{
#	echo "process $1"
	curl --insecure --silent -X GET \
		-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$1/qemu | jq -r '.data[]' >/tmp/proxmox/out_$1.json 2>>$CURLLOG
	err=$?
	if ! [ $err = 0 ]
	then
		echo "node '$1': echec!"
		exit 1
	fi
# we use the '_' character to separate fields because in the json file, multiple tags are separated with ';'
# (and '_' is not allowed in the VM name field)
	jq -r '(.vmid|tostring) + "_" + .name + "_" + .tags + "_" + (.template|tostring)' < /tmp/proxmox/out_$1.json >/tmp/proxmox/out_$1.csv

# replace null by 0 (machine not a template), just to make it prettier
	sed -i -e 's/_null/_0/g' /tmp/proxmox/out_$1.csv

# replace the semi-colon separating tags with a comma
	sed -i -e 's/;/,/g' /tmp/proxmox/out_$1.csv

# replace the underscore by semi-colon
	sed -i -e 's/_/;/g' /tmp/proxmox/out_$1.csv

# sort by name
	sort --key=1 /tmp/proxmox/out_$1.csv >data_out_$1.csv
	
# Add node name on each line, first position
	IFS=";";while read line;
	do
		echo "$1;${line}" >> $OUT
 	done < data_out_$1.csv

	# extraction des template de chaque node
	NBT=0
	rm template_$1.csv 2>/dev/null
	IFS=";";while read -a ARR
	do
#		echo "0:${ARR[0]} - 1:${ARR[1]} - 2:${ARR[2]} - 3:${ARR[3]}"
		if [ ${ARR[3]} = 1 ]
		then
			NBT=$((NBT+1))
			echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_$1.csv
			echo "$1;${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_all.csv
		fi

# comptage du nb d'occurrence pour chaque tag
# TODO: supprimer quand on aura les csv par tag
		if ! [ "${ARR[2]}" = "" ]
		then
			tags=${ARR[2]}
			IFS=","; read -a ARR2 <<< "$tags"; IFS=";"
			for ((i=0;i<${#ARR2[@]}; i++))
			do
				tag=${ARR2[$i]}
				((TAGARR[$tag]++))
				echo "$tag">>/tmp/proxmox/tags.csv
			done
		fi
	done < data_out_$1.csv

	NBTOT=$(wc -l <data_out_$1.csv)
	((NBVM=NBTOT-NBT))
	printf "| %10s | %3d | %7d | %5d |\n" $1 $NBVM $NBT $NBTOT
	((TOT1+=NBVM))
	((TOT2+=NBT))
	((TOT3+=NBTOT))
}

#---------------------------------------------------------------------------
# Get list of nodes
if [ "$DEBUG" = "NO" ]; then clear; fi

#echo "-Récupération liste des nodes..."
curl --silent -k \
	-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
	https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes|jq | jq -r '.data[] | .node' >data_nodes.csv 2>>$CURLLOG
err=$?
if ! [ $err = 0 ];
then
	echo "Error: API call failure, err=$?"
	exit 1
fi

rm /tmp/proxmox/tags.csv 2>/dev/null
rm data_template_* 2>/dev/null

# associative array used to count tags
declare -A TAGARR

echo "|    Node    | #VM | #Templ. |  Tot  |"
echo "|------------+-----+---------+-------|"
 
TOT1=0
TOT2=0
TOT3=0

while read -r nodename
do
	process $nodename
done < data_nodes.csv

echo "|------------+-----+---------+-------|"
printf "      Totaux | %3d | %7d | %5d |\n" $TOT1 $TOT2 $TOT3

echo -e "\n-Liste des $(wc -l<data_template_all.csv) templates:"
printf "| %10s | %13s | %15s | %7s |\n" Node Name Tags VMid
echo "|------------+---------------+-----------------+---------|"
IFS=";";while read -a ARR
do
	printf "| %10s | %13s | %15s | %7s |\n" ${ARR[0]} ${ARR[1]} ${ARR[2]} ${ARR[3]}
done < data_template_all.csv
echo "|------------+---------------+-----------------+---------|"

sort /tmp/proxmox/tags.csv >/tmp/proxmox/tags1.csv
uniq /tmp/proxmox/tags1.csv >data_tags.csv

echo -e "\n-Tags: $(wc -l <data_tags.csv)"
echo -e "|    Tags    | VM+T. |\n|------------+-------|"
for i in "${!TAGARR[@]}"
do
	printf "| %10s | %5d |\n" $i ${TAGARR[$i]}
	((COMPT+=${TAGARR[$i]}))
done
echo "|------------+-------|"
printf "       Total | %5d |\n" $COMPT

#===========================================================
# Generate a csv file for each tag, holding the type (Vm/T), the VMID, the name, and the node

rm data_tag_* 2>/dev/null
IFS=";";while read -a TAG
do
#	echo "TAG=$TAG"
	while read -a ARR
	do
#		echo "ARR[3]=${ARR[3]}"
		tags=${ARR[3]}
		IFS=","; read -a ARR2 <<< "$tags"; IFS=";"
		for i in ${ARR2[@]}
		do
			if [ "$i" = "$TAG" ]; then
				echo "${ARR[0]};${ARR[1]};${ARR[2]};${ARR[4]};${ARR[3]}" >>data_tag_$TAG.csv
			fi
		done
	done <$OUT
done <data_tags.csv



#===========================================================
# Generate a csv file for each group, holding the users

curl --insecure --silent -X GET \
	-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
	"https://${APINODE}.univ-rouen.fr:8006/api2/json/access/users?full=1" | jq '.data[]' >/tmp/proxmox/users.json

err=$?
if [ $err != 0 ]; then
	echo "Error: failure of operation, err=$err";
	exit 1
fi

# convert json into 3-fields CSV file
jq -r '.userid + ";" + .groups + ";" + .email'</tmp/proxmox/users.json >/tmp/proxmox/users.csv

sort /tmp/proxmox/users.csv >data_users.csv
#echo -e "\n-Nb utilisateurs enregistrés: $(wc -l<data_users.csv) "

# build one file per group
rm data_group_*.csv 2>/dev/null
declare -A NBUSGR
if [ -f /tmp/proxmox/groups1.csv ]; then rm /tmp/proxmox/groups1.csv; fi
IFS=";";while read -a TAB
do
	GR=${TAB[1]}
	echo "$GR">>/tmp/proxmox/groups1.csv
	if ! [ "$GR" = "" ]; then
		echo "${TAB[0]};${TAB[2]}" >> data_group_${GR}.csv
	else
		echo "${TAB[0]};${TAB[2]}" >> data_group_NOGROUP.csv
	fi
done <data_users.csv

sort /tmp/proxmox/groups1.csv >/tmp/proxmox/groups2.csv
uniq /tmp/proxmox/groups2.csv >data_groups.csv

echo -e "\n|         Group           | #Users |\n|-------------------------+--------|"
COMPT=0
IFS=";";while read groupname
do
	if ! [ "$groupname" = "" ]; then
		nb=$(wc -l <data_group_${groupname}.csv)
		printf "| %23s | %6d |\n" $groupname $nb
		((COMPT+=nb))
	fi
done <data_groups.csv
NBNOGROUP=$(wc -l <data_group_NOGROUP.csv)
printf "|           (no group)    | %6d |\n" $NBNOGROUP
((COMPT+=NBNOGROUP))
echo "|-------------------------+--------|"
printf "                  Total   | %6d |\n" $COMPT

exit 0




