#!/bin/bash

# nom: pgvm_view
# Visualisation des machines d'un node

# ce script doit être appelé depuis le script maitre pgvm

# -x pour debug
set +x

# désactive l'interprétation de '!' dans une chaine
set +H

VNODE=$(zenity --list --text="Quel node?" --column="node" anvers gand bruxelles)
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

echo "Liste des $(wc -l<out_$VNODE.csv) machines du node '$VNODE'"
printf "| VM/T |        Nom       |     Id     |   Tags   |\n";
printf "|------+------------------+------------+----------|\n"

IFS=";";while read -a TAB
do
	if [ ${TAB[3]} == 1 ]; then
		printf "|  T   |"
	else
		printf "|  VM  |"
	fi
	printf " %16s | %10d | %8s |\n" ${TAB[1]} ${TAB[0]} ${TAB[2]}
done <out_$VNODE.csv
printf "|------+------------------+------------+----------|\n"

exit 0


