#!/bin/bash

# nom: pgvm_users
# Visualisation des utilisateurs enregistrés

# ce script doit être appelé depuis le script maitre pgvm

# -x pour debug
set +x

# désactive l'interprétation de '!' dans une chaine
set +H


# create an array holding the group names, just for the zenity call below
declare -a GROUPARR
while read -r group
do
	GROUPARR+=($group)
done < data_groups.csv

GROUPARR+=("(Sans groupe)")

#echo "GROUPARR=${GROUPARR[@]}"

GROUP=$(zenity --list --height=300 --text="Quel groupe?" --column="groupes" "${GROUPARR[@]}")
if [ $? != 0 ]; then
	echo "Interruption"; exit 1
fi

#echo "GROUP=$GROUP"
if [ "$GROUP" = "(Sans groupe)" ]; then
	GROUPFILE=data_group_NOGROUP.csv
else
	GROUPFILE=data_group_$GROUP.csv
fi

clear
GROUPSIZE=$(wc -l <$GROUPFILE)
echo "-Groupe '$GROUP': $GROUPSIZE utilisateurs"

printf "|       Id       |                   email                  |\n";
printf "|----------------+------------------------------------------|\n"

IFS=";";while read -a TAB
do
#	if [ "$GROUP" = "${TAB[1]}" ];
#	then
		printf "| %14s | %-40s |\n" ${TAB[0]} ${TAB[1]}
#	fi
done <$GROUPFILE
printf "|----------------+------------------------------------------|\n"

exit 0


