#!/bin/bash

# name: pgvm ("Proxmox Gestion VM")
# S. Kramm, URN, 2026

# All API calls will be done on this one.
# In case it breaks, just change to another one
APINODE=anvers
DEBUG=YES

if [ "$1" = "" ]
then
	echo "Erreur, donner en argument le fichier de credentials"
	exit 1
fi
TOKEN_FILE=$1

# vérification de l'accès au fichier
if ! [ -f $TOKEN_FILE ];
then
	echo "Erreur, fichier '$TOKEN_FILE' introuvable!"
	exit 1
fi
source $TOKEN_FILE

export PVUSER
export TOK_VALUE
export TOK_NAME
export REALM
export CURLLOG
export APINODE

# Check that zenity is available
which zenity >/dev/null
if [ $? = 1 ]
then
	echo "Error: zenity not available, please install"
	exit 1
fi

TODAY=$(date '+%Y%m%d_%H%M%S')
CURLLOG=/tmp/proxmox/curl_$TODAY.log

# temporary files are stored over there
mkdir -p /tmp/proxmox

# TODO: bug, en cas de non réponse, pas de message d'erreur !!
# test de la réponse de l'API
echo "-Test de la réponse de l'API"
response=$(./pgvm_api_call GET https://${APINODE}.univ-rouen.fr:8006/api2/json/version)
if ! [ $? = 0 ]; then
	exit 1
fi
#echo "response=$response"
echo "-connection API: fonctionnelle!"

./pgvm_list

items=("Génération inventaire" "Liste VMs par Node" "Création VMs" "Suppression VMs" "Liste users" "Liste par tag")

while item=$(zenity --height=400 --list \
	--title="Menu principal" \
	--text="Choix" \
	--column="Options" "${items[@]}")
do
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	case "$item" in
		"${items[0]}") ./pgvm_list;;
		"${items[1]}") ./pgvm_view;;
		"${items[2]}") ./pgvm_create; ./pgvm_list;;
		"${items[3]}") ./pgvm_delete; ./pgvm_list;;
		"${items[4]}") ./pgvm_users;;
		"${items[5]}") ./pgvm_tags;;
		*) echo "Ooops! Invalid option.";;
	esac
done

rm /tmp/proxmox/* 2>/dev/null
echo "fini!"


