#!/usr/bin/env bash

# name: pgvm ("Proxmox Gestion VM")
# S. Kramm, URN, 2026
# https://github.com/skramm/proxmox_automation


# TODO bug: une fois des machines avec un tag créer, quand on les supprime, le tag reste à une valeur incorrecte

if [ "$1" = "" ]
then
	echo "Erreur, donner en argument le fichier de credentials"
	exit 1
fi
TOKEN_FILE=$1

# Check that file holding credentials is there
if ! [ -f $TOKEN_FILE ];
then
	echo "Erreur, fichier '$TOKEN_FILE' introuvable!"
	exit 1
fi
source $TOKEN_FILE

# TODO: this will be useless once all the code will be in a single file
export PVUSER
export TOK_VALUE
export TOK_NAME
export REALM
export CURLLOG
export APINODE
export DOMAIN
export PORT


#================================================================
function ApiCall()
{
	if [ "$DEBUG" = "Y" ]; then
		if [ "$2" = "" ]
		then
			echo "Internal error, endpoint missing"
			exit 1
		fi
		if [ "$1" = "" ]
		then
			echo "Internal error, POST or GET missing"
			exit 1
		fi
	fi

# if no response within 5 s., abort
	response=$(curl --insecure \
		--connect-timeout 5 \
		--silent -X $1 \
		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
		"$2")
	err=$?
	if ! [ $err = 0 ];
	then
		echo "Error: API call failure, HTTP method='$1', endpoint='$2'"
		echo -e " -curl return value: $err\n -API response: $response"
		exit 1
	fi
}



#================================================================
# Fetch data of a given node ($1), called by FetchData()
function ProcessNode()
{
	if [ "$DEBUG" = "Y" ];then echo "ProcessNode(): $1"; fi
	
	ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$1/qemu?full=1"
	jq -r '.data[]' <<< "$response" >/tmp/proxmox/node_$1.json 2>>$CURLLOG 

# we use the '_' character to separate fields because in the json file, multiple tags are separated with ';'
# (and '_' is not allowed in the VM name field)
	jq -r '(.vmid|tostring) + "_" + .name + "_" + .tags + "_" + (.template|tostring) + "_" + .status' < /tmp/proxmox/node_$1.json >/tmp/proxmox/node_$1.csv

# replace null by 0 (machine is not a template), just to make it prettier
	sed -i -e 's/_null/_0/g' /tmp/proxmox/node_$1.csv

# replace the semi-colon separating tags with a comma
	sed -i -e 's/;/,/g' /tmp/proxmox/node_$1.csv

# replace the underscore by semi-colon
	sed -i -e 's/_/;/g' /tmp/proxmox/node_$1.csv

# sort by name
	sort --key=1 /tmp/proxmox/node_$1.csv >data_node_$1.csv
	
# Add node name on each line, first position
	IFS=";";while read line;
	do
		echo "$1;${line}" >> data_node_ALL.csv
 	done < data_node_$1.csv

	IFS=";";while read -a ARR
	do
# comptage du nb d'occurrence pour chaque tag
# TODO: supprimer quand on aura les csv par tag
		if ! [ "${ARR[2]}" = "" ]
		then
			tags=${ARR[2]}
			IFS=","; read -a ARR2 <<< "$tags"; IFS=";"
			for ((i=0;i<${#ARR2[@]}; i++))
			do
				tag=${ARR2[$i]}
				((TAGAARR[$tag]++))
				echo "$tag">>/tmp/proxmox/tags.csv
			done
		fi
	done < data_node_$1.csv
}


#================================================================
# Fetch all the data
# This function does not print anything
function FetchData()
{
	if [ "$DEBUG" = "Y" ]; then echo "FetchData()"; fi

# clean out old data
	rm /tmp/proxmox/tags.csv 2>/dev/null
	rm data_* 2>/dev/null
	TAGAARR=()
	
# Fetch list of nodes
	ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes"
	jq  -r '.data[] | .node' <<<"$response" >data_nodes.csv 2>>$CURLLOG

# Main API loop, iterate on all nodes and collect all the nodes data
	while read -r NODE
	do
# step 1: fetch all the machines on that node
		ProcessNode $NODE

# step 2: build data file holding templates
		IFS=";"; while read -a ARR
		do
			if [ ${ARR[3]} = 1 ]; then
				((NBT++))
				echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_$NODE.csv
				echo "$NODE;${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_ALL.csv
			fi
		done < data_node_$NODE.csv

	done <data_nodes.csv

	sort /tmp/proxmox/tags.csv >/tmp/proxmox/tags1.csv
	uniq /tmp/proxmox/tags1.csv >data_tags.csv

# Generate a csv file for each tag, holding the type (Vm/T), the VMID, the name, and the node
	IFS=";";while read -a TAG
	do
		while read -a ARR
		do
	#		echo "ARR[3]=${ARR[3]}"
			tags=${ARR[3]}
			IFS=","; read -a ARR2 <<< "$tags"; IFS=";"
			for i in ${ARR2[@]}
			do
				if [ "$i" = "$TAG" ]; then
					echo "${ARR[0]};${ARR[1]};${ARR[2]};${ARR[4]};${ARR[3]}" >>data_tag_$TAG.csv
				fi
			done
		done <data_node_ALL.csv
	done <data_tags.csv

# Generate a csv file for each group, holding the users
	ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/users?full=1"
	jq -r '.data[]' <<<$response >/tmp/proxmox/users.json

# convert json into 3-fields CSV file
	jq -r '.userid + ";" + .groups + ";" + .email'</tmp/proxmox/users.json >/tmp/proxmox/users.csv

	sort /tmp/proxmox/users.csv >data_users.csv
	#echo -e "\n-Nb utilisateurs enregistrés: $(wc -l<data_users.csv) "

	# build one file per group
	rm data_group_*.csv 2>/dev/null

	if [ -f /tmp/proxmox/groups1.csv ]; then rm /tmp/proxmox/groups1.csv; fi
	IFS=";";while read -a TAB
	do
		GR=${TAB[1]}
		echo "$GR">>/tmp/proxmox/groups1.csv
		if ! [ "$GR" = "" ]; then
			echo "${TAB[0]};${TAB[2]}" >> data_group_${GR}.csv
		else
			echo "${TAB[0]};${TAB[2]}" >> data_group_NOGROUP.csv
		fi
	done <data_users.csv

	sort /tmp/proxmox/groups1.csv >/tmp/proxmox/groups2.csv
	uniq /tmp/proxmox/groups2.csv >data_groups.csv
}


#================================================================
function ShowNodes()
{
	echo "|    Node    | #VM | #Templ. |  Tot  ||  ON | OFF |"
	echo "|------------+-----+---------+-------||-----|-----|"

	TOTVM=0
	TOTT=0
	TOTALL=0
	TOTON=0
	TOTOFF=0
	while read -r NODE
	do
		NBON=0
		NBOFF=0
		NBTOT=$(wc -l <data_node_$NODE.csv)
		NBT=0
		if [ -f data_template_$NODE.csv ]; then
			NBT=$(wc -l <data_template_$NODE.csv)
		fi	
		((NBVM=NBTOT-NBT))
		IFSOLD=$IFS
		IFS=";"; while read -a ARR
		do
			if [ "${ARR[4]}" = "running" ]; then
				((NBON++))
			fi
			if [ "${ARR[4]}" = "stopped" ]; then
				((NBOFF++))
			fi
		done <data_node_$NODE.csv
		IFS=$IFSOLD
		
		printf "| %10s | %3d | %7d | %5d || %3d | %3d |\n" $NODE $NBVM $NBT $NBTOT $NBON $NBOFF
		((TOTVM+=NBVM))
		((TOTT+=NBT))
		((TOTALL+=NBTOT))
		((TOTON+=NBON))
		((TOTOFF+=NBOFF))
	done < data_nodes.csv

	echo "|------------+-----+---------+-------||-----|-----|"
#	echo "|------------+-----+---------+-------|"
	printf "      Totaux | %3d | %7d | %5d || %3d | %3d |\n" $TOTVM $TOTT $TOTALL $TOTON $TOTOFF
}

#================================================================
function ShowTemplates()
{
	echo -e "\n-Liste des $(wc -l<data_template_ALL.csv) templates:"
	printf "| %12s | %13s | %15s | %7s |\n" Node Name Tags VMid
	echo "|--------------+---------------+-----------------+---------|"
	IFS=";";while read -a ARR
	do
		printf "| %12s | %13s | %15s | %7s |\n" ${ARR[0]} ${ARR[1]} ${ARR[2]} ${ARR[3]}
	done < data_template_ALL.csv
	echo "|--------------+---------------+-----------------+---------|"
}

#================================================================
function ShowTags()
{
	COMPT=0
	printf "\n|   %2d Tags  | #VM+T. |\n|------------+--------|\n" $(wc -l <data_tags.csv)
	while read TAG
	do
		if [ "$TAG" = " " ]; then
			printf "| (sans tag) | %6d |\n" ${TAGAARR[$TAG]}
		else
			printf "| %10s | %6d |\n" $TAG ${TAGAARR[$TAG]}
		fi
		((COMPT+=${TAGAARR[$TAG]}))
	done <data_tags.csv
	echo "|------------+--------|"
	printf "       Total | %6d |\n" $COMPT
}

#================================================================
function ShowGroups()
{
	echo -e "\n-Nb d'utilisateurs: $(wc -l <data_users.csv), répartis dans $(wc -l <data_groups.csv) groupes"
	echo -e "|         Group           | #Users |\n|-------------------------+--------|"
	COMPT=0
	IFS=";";while read groupname
	do
		if ! [ "$groupname" = "" ]; then
			nb=$(wc -l <data_group_${groupname}.csv)
			printf "| %23s | %6d |\n" $groupname $nb
			((COMPT+=nb))
		fi
	done <data_groups.csv

	NBNOGROUP=$(wc -l <data_group_NOGROUP.csv)
	printf "|           (no group)    | %6d |\n" $NBNOGROUP
	((COMPT+=NBNOGROUP))
	echo "|-------------------------+--------|"
	printf "                  Total   | %6d |\n" $COMPT
}

#================================================================
function ShowDashboard()
{
	ShowNodes
	ShowTemplates
	ShowTags
	ShowGroups
}

#================================================================
# Delete a set of VM holding a given tag
function DeleteVmByTag()
{
	if ! [ -f data_tags.csv ]
	then
		echo "Erreur, fichier 'data_tags.csv' inaccessible"
		exit 1
	fi

	unset TAGARR
	declare -a TAGARR
	IFS=";";while read TAG
	do
		TAGARR+=($TAG)
	done <data_tags.csv
	#echo "TAGARR=${TAGARR[@]}"	

	TAGDEL=$(zenity --list --height=300 \
		--text="Quel machines ayant le tag ci-dessous souhaitez-vous détruire?" --column="tags" ${TAGARR[@]})
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

# count VM only (not templates, as these will not be deleted)
#echo "TAGDEL=$TAGDEL"
	COUNT=0
	IFS=";";while read -a ARR
	do
		if [ ${ARR[3]} = 0 ]; then ((COUNT++)); fi
	done < data_tag_${TAGDEL}.csv

	zenity --question --text \
		"Ok pour effacer les ${COUNT} VMs associées au tag $TAGDEL?"
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi


#-------------------------
# Delete VMs
# TODO: pas plus simple de lire dans le fichier tags_XXXX.csv ???

COMPT=0
IFS=";";while read -a TAB
do
	if ! [ "${TAB[3]}" = "" ]; then
		IFS=","; read -r -a TAGS <<< "${TAB[3]}"; IFS=";"
		for ((i=0; i<${#TAGS[@]}; i++))
		do
			tag=${TAGS[$i]}
#				echo "node ${TAB[0]}: machine ${TAB[2]}, tag=$tag"
			if [ $tag = $TAGDEL ]; then
				if [ "${TAB[4]}" = "1" ]; then
					echo "node ${TAB[0]}: machine ${TAB[2]}, id=${TAB[1]} est un template, pas de suppression"
				else
					echo "node ${TAB[0]}: suppression machine ${TAB[2]}, id=${TAB[1]}"
					ApiCall DELETE "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}"
#					response=$(curl --insecure --silent -X DELETE \
#						-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
#						"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}")
#					err=$?

#					if [ $err != 0 ]; then
#						echo "Error: failure of delete operation, err=$err, response='$response'";
#						exit 1
#					fi
					((COMPT++))
				fi
			fi
		done
	fi
done <data_node_ALL.csv

echo "-$COMPT VM supprimées, appuyer sur une touche"
read
}


#================================================================
# Show list of VM holding a given tag
function ViewVmByTag()
{
	# re-create an array holding the tag names
	unset TAGARR
	declare -a TAGARR
	while read -r tagname
	do
		TAGARR+=($tagname)
	done < data_tags.csv

	VTAG=$(zenity --list --height=300 --text="Quel tag?" --column="Tags" "${TAGARR[@]}")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	if [ "$DEBUG" = "N" ]; then clear; fi
	echo -e "\n-Liste des $(wc -l<data_tag_$VTAG.csv) machines ayant le tag '$VTAG':"
	printf "| VM/T |      Node     |       Nom       |    VMId     |      Tags       |\n";
	printf "|------+---------------+-----------------+-------------+-----------------|\n"

	IFS=";";while read -a TAB
	do
		if [ ${TAB[3]} == 1 ]; then
			printf "|  T   |"
		else
			printf "|  VM  |"
		fi
		printf " %-13s | %-15s | %11d | %15s |\n" ${TAB[0]} ${TAB[2]} ${TAB[1]} ${TAB[4]} 
	done <data_tag_$VTAG.csv
	printf "|------+---------------+-----------------+-------------+-----------------|\n"
}


#================================================================
# Show list of users in a given group
function ViewGroups()
{
# create an array holding the group names, just for the zenity call below
	unset GROUPARR
	declare -a GROUPARR
	while read -r group
	do
		GROUPARR+=($group)
	done < data_groups.csv

	GROUPARR+=("(Sans groupe)")

	GROUP=$(zenity --list --height=300 --text="Quel groupe?" --column="groupes" "${GROUPARR[@]}")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	#echo "GROUP=$GROUP"
	if [ "$GROUP" = "(Sans groupe)" ]; then
		GROUPFILE=data_group_NOGROUP.csv
	else
		GROUPFILE=data_group_$GROUP.csv
	fi

	if [ "$DEBUG" = "N" ]; then clear; fi
	GROUPSIZE=$(wc -l <$GROUPFILE)
	echo "-Groupe '$GROUP': $GROUPSIZE utilisateurs"

	printf "|       Id       |                   email                  |\n";
	printf "|----------------+------------------------------------------|\n"

	IFS=";";while read -a TAB
	do
		printf "| %14s | %-40s |\n" ${TAB[0]} ${TAB[1]}
	done <$GROUPFILE
	printf "|----------------+------------------------------------------|\n"
}


#================================================================
# Show list of VM on a given node
function ViewVmByNode()
{
# re-create an array holding the nodes names
	unset NODEARR
	declare -a NODEARR
	while read -r nodename
	do
		NODEARR+=($nodename)
	done < data_nodes.csv

	VNODE=$(zenity --list --text="Quel node?" --column="node" "${NODEARR[@]}")
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	if ! [ "$DEBUG" = "N" ]; then clear; fi
	echo -e "\n-Liste des $(wc -l<data_node_$VNODE.csv) machines du node '$VNODE':"
	printf "| VM/T |    |        Nom       |    VMId    |     Tags      |\n";
	printf "|------+----+------------------+------------+---------------|\n"
	NBON=0
	IFS=";";while read -a TAB
	do
		if [ ${TAB[3]} == 1 ]; then
			printf "|  T   | - "
		else
			printf "|  VM  | "

			if [ ${TAB[4]} = "stopped" ]; then
				echo -n "🔴"
			else
				echo -n "🟢"
				((NBON++))
			fi
		fi
		printf " | %-16s | %10d | %13s |\n" ${TAB[1]} ${TAB[0]} ${TAB[2]}
	done <data_node_$VNODE.csv
	printf "|------+----+------------------+------------+---------------|\n"

	NBT=0
	if [ -f data_template_$VNODE.csv ]; then
		NBT=$(wc -l <data_template_$VNODE.csv)
	fi

	NBTOT=$(wc -l <data_node_$VNODE.csv)
	((NBVM=NBTOT-NBT))
	echo "Bilan: $NBT templates et $NBVM VM, dont $NBON en fonctionnement"
}

#================================================================
function ToolCheck()
{
	which $1 >/dev/null
	if ! [ $? = 0 ]; then
		echo "Error: program '$1' not available, please install"
		exit 1
	fi
}
#================================================================
function VarCheck()
{
	if [ "$1" = "" ]; then
		echo "Error: variable '$2' is empty, please check manual and file '$TOKEN_FILE'"
		exit 1
	fi
}


#================================================================
# PROGRAM START
#================================================================

# Check that required tools are available
ToolCheck curl
ToolCheck jq
ToolCheck zenity

# Check that these variables are not empty
VarCheck $TOK_VALUE TOK_VALUE
VarCheck $TOK_NAME TOK_NAME
VarCheck $REALM REALM
VarCheck $PVUSER PVUSER
VarCheck $APINODE APINODE
VarCheck $DOMAIN DOMAIN
VarCheck $PORT PORT

TODAY=$(date '+%Y%m%d_%H%M%S')
CURLLOG=/tmp/proxmox/curl_$TODAY.log

# All temporary files are stored over there
mkdir -p /tmp/proxmox

# TODO: bug, en cas de non réponse, pas de message d'erreur !!
# test de la réponse de l'API
echo "-Test de la réponse de l'API"
ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/version"
echo "-connection API: fonctionnelle!"

# Associative array used to count tags
unset TAGAARR
declare -A TAGAARR

FetchData
ShowDashboard

items=("Affichage Dashboard" \
	"Liste VMs par node" \
	"Liste VMs par tag" \
	"Création VMs" \
	"Suppression VMs par tag" \
	"Liste des users par groupe")

while item=$(zenity --height=400 --width=300 --list \
	--title="Menu principal" \
	--text="Choix" \
	--column="Options" "${items[@]}")
do
	if [ $? != 0 ]; then
		echo "Interruption"; exit 1
	fi

	case "$item" in
		"${items[0]}") FetchData; ShowDashboard;;
		"${items[1]}") ViewVmByNode;;
		"${items[2]}") ViewVmByTag;;
		"${items[3]}") ./pgvm_create; FetchData; ShowDashboard;;
		"${items[4]}") DeleteVmByTag; FetchData; ShowDashboard;;
		"${items[5]}") ViewGroups;;
		*) echo "Ooops! Invalid option.";;
	esac
done

if ! [ "$DEBUG" = "Y" ]; then rm /tmp/proxmox/* 2>/dev/null; fi
echo "fini!"


