#!/bin/bash

# name: pgvm_api_call
# S. Kramm, URN, 2026

#echo "a1=-$1- a2=-$2-"
#echo "PVUSER=${PVUSER}\nREALM=${REALM}\nTOK_NAME=${TOK_NAME}\nTOK_VALUE=${TOK_VALUE}"

if [ "$2" = "" ]
then
	echo "Internal error, endpoint missing"
	exit 1
fi

if [ "$1" = "" ]
then
	echo "Internal error, POST or GET missing"
	exit 1
fi

# faut-il vraiment tout tester???
if [ "$PVUSER" = "" ];
then
	echo "Internal error, PVUSER not defined"
	exit 1
fi
#set -x

# if no response within 5 s., abort
response=$(curl --insecure \
	--connect-timeout 5 \
	--silent -X $1 \
	-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
	"$2")
err=$?
echo "err=$err"
if ! [ $err = 0 ];
then
	echo "Error: API call failure, HTTP method='$1', endpoint='$2'"
	echo "curl response: $response"
	exit 1
fi

exit 0


